name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Repository
        run: cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/${{ github.actor }}/loopback2-angular4-seed/loopback2-angular4-seed
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
