name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/${{ github.actor }}/loopback2-angular4-seed/loopback2-angular4-seed
          username: ${{ github.actor }}
          password: ${{ github.token }}
